select distinct accountdto0_.id as id1_2_0_
	 , branchcomm2_.id as id1_49_1_
	 , accountcli3_.account_id as account_1_13_2_
	 , accountbal4_.id as id1_0_3_
	 , accountdto0_.abs_notification as abs_noti2_2_0_
	 , accountdto0_.account_active_passive as account_3_2_0_
	 , accountdto0_.account_balance_dto_id as account_4_2_0_
	 , accountdto0_.account_name as account_5_2_0_
	 , accountdto0_.account_number as account_6_2_0_
	 , accountdto0_.account_type_dto_id as account_7_2_0_
	 , accountdto0_.bic as bic8_2_0_
	 , accountdto0_.block_date as block_da9_2_0_
	 , accountdto0_.block_reason as block_r10_2_0_
	 , accountdto0_.block_type as block_t11_2_0_
	 , accountdto0_.branch_common_dto_id as branch_12_2_0_
	 , accountdto0_.client_kpp as client_13_2_0_
	 , accountdto0_.close_date as close_d14_2_0_
	 , accountdto0_.comment as comment15_2_0_
	 , accountdto0_.cur_alphabetic_code as cur_alp16_2_0_
	 , accountdto0_.cur_numeric_code as cur_num17_2_0_
	 , accountdto0_.currency as currenc18_2_0_
	 , accountdto0_.fbank as fbank19_2_0_
	 , accountdto0_.irreducable_sum_available as irreduc20_2_0_
	 , accountdto0_.kib_available as kib_ava21_2_0_
	 , accountdto0_.last_modify_date as last_mo22_2_0_
	 , accountdto0_.master_abs as master_23_2_0_
	 , accountdto0_.money_owner_deputed_acc as money_o24_2_0_
	 , accountdto0_.open_date as open_da25_2_0_
	 , accountdto0_.overnight_account as overnig26_2_0_
	 , accountdto0_.payer_deputed_acc as payer_d27_2_0_
	 , accountdto0_.third_acc_bankru_bic as third_a28_2_0_
	 , accountdto0_.third_party_account as third_p29_2_0_
	 , accountdto0_.version as version30_2_0_
	 , accountdto0_.visible_for_dbo as visible31_2_0_
	 , branchcomm2_.bank_int as bank_int2_49_1_
	 , branchcomm2_.bank_ru as bank_ru3_49_1_
	 , branchcomm2_.bic as bic4_49_1_
	 , branchcomm2_.branch_code as branch_c5_49_1_
	 , branchcomm2_.branch_type as branch_t6_49_1_
	 , branchcomm2_.city_id as city_id7_49_1_
	 , branchcomm2_.code_tfu as code_tfu8_49_1_
	 , branchcomm2_.comments as comments9_49_1_
	 , branchcomm2_.corr_accounts as corr_ac10_49_1_
	 , branchcomm2_.full_name as full_na11_49_1_
	 , branchcomm2_.head_branch_id as head_br12_49_1_
	 , branchcomm2_.inf_res_acc_online as inf_res13_49_1_
	 , branchcomm2_.is_not_active as is_not_14_49_1_
	 , branchcomm2_.kpp as kpp15_49_1_
	 , branchcomm2_.master_abs as master_16_49_1_
	 , branchcomm2_.res_acc_online as res_acc17_49_1_
	 , branchcomm2_.short_name as short_n18_49_1_
	 , branchcomm2_.short_name_int as short_n19_49_1_
	 , branchcomm2_.swift_code as swift_c20_49_1_
	 , branchcomm2_.time_zone as time_zo21_49_1_
	 , branchcomm2_.version as version22_49_1_
	 , accountcli3_.inn as inn2_13_2_
	 , accountcli3_.short_name as short_na3_13_2_
	 , accountbal4_.actual_balance as actual_b2_0_3_
	 , accountbal4_.actual_balance_rub as actual_b3_0_3_
	 , accountbal4_.actual_date_time as actual_d4_0_3_
	 , accountbal4_.available_balance as availabl5_0_3_
	 , accountbal4_.blocked_sum as blocked_6_0_3_
	 , accountbal4_.blocked_sum_rub as blocked_7_0_3_
	 , accountbal4_.carded_sum as carded_s8_0_3_
	 , accountbal4_.cart as cart9_0_3_
	 , accountbal4_.gos_balance as gos_bal10_0_3_
	 , accountbal4_.irreducible_balance as irreduc11_0_3_
	 , accountbal4_.is_blocked as is_bloc12_0_3_
	 , accountbal4_.month_limit_balance as month_l13_0_3_
	 , accountbal4_.overdraft_sum as overdra14_0_3_
	 , accountbal4_.planing_balance as planing15_0_3_
	 , accountbal4_.version as version16_0_3_
  from stmt.st_acc_account_dto accountdto0_
  join stmt.st_acc_account_client_relation accountcli1_
    on accountcli1_.account_id = accountdto0_.id
   and ($5=$6 or $7=$8 and accountcli1_.client_id in ($1))
  left join stmt.st_branch_common branchcomm2_
    on branchcomm2_.id = accountdto0_.branch_common_dto_id
  left join stmt.st_account_client_extension accountcli3_
    on accountcli3_.account_id = accountdto0_.id
  left join stmt.st_acc_account_balance_dto accountbal4_
    on accountbal4_.id = accountdto0_.account_balance_dto_id
 where (accountdto0_.visible_for_dbo = $2 or accountdto0_.third_party_account = $3)
 order by accountdto0_.id asc
 limit $4;