select paymentcla0_.id as id1_50_
     , paymentcla0_.archive_date as archive_2_50_
     , paymentcla0_.branch_ext_id as branch_e3_50_
     , paymentcla0_.channel as channel4_50_
     , paymentcla0_.client_ext_id as client_e5_50_
     , paymentcla0_.create_date as create_d6_50_
     , paymentcla0_.delete_date as delete_d7_50_
     , paymentcla0_.document_date as document8_50_
     , paymentcla0_.document_number as document9_50_
     , paymentcla0_.document_number_as_num as documen10_50_
     , paymentcla0_.edoc_ref_id as edoc_re11_50_
     , paymentcla0_.exporting_to_abs as exporti12_50_
     , paymentcla0_.import_date as import_13_50_
     , paymentcla0_.last_modify_date as last_mo14_50_
     , paymentcla0_.last_modify_user_ext_id as last_mo15_50_
     , paymentcla0_.last_modify_user_snapshot as last_mo16_50_
     , paymentcla0_.note_from_receiver as note_fr17_50_
     , paymentcla0_.read as read18_50_
     , paymentcla0_.receive_date as receive19_50_
     , paymentcla0_.send_date as send_da20_50_
     , paymentcla0_.source_id as source_21_50_
     , paymentcla0_.status_action as status_22_50_
     , paymentcla0_.status_bank_backend_response_message as status_23_50_
     , paymentcla0_.status_base as status_24_50_
     , paymentcla0_.status_comment as status_25_50_
     , paymentcla0_.status_extended as status_26_50_
     , paymentcla0_.note_from_bank_author as note_fr27_50_
     , paymentcla0_.note_from_bank_comment as note_fr28_50_
     , paymentcla0_.note_from_bank_create_date as note_fr29_50_
     , paymentcla0_.note_from_bank_fio as note_fr30_50_
     , paymentcla0_.type_id as type_id31_50_
     , paymentcla0_.uuid as uuid32_50_
     , paymentcla0_.acceptance_period as accepta33_50_
     , paymentcla0_.acceptance_period_end_date as accepta34_50_
     , paymentcla0_.amount as amount35_50_
     , paymentcla0_.amount_full as amount_36_50_
     , paymentcla0_.amount_pure as amount_37_50_
     , paymentcla0_.cabs_doc_ref as cabs_do38_50_
     , paymentcla0_.cabs_doc_ref_ext as cabs_do39_50_
     , paymentcla0_.card_to_date as card_to40_50_
     , paymentcla0_.commission as commiss41_50_
     , paymentcla0_.commission_type as commiss42_50_
     , paymentcla0_.currency_code as currenc43_50_
     , paymentcla0_.collection_outgoing_payment_claim_date as collect44_50_
     , paymentcla0_.external_id as externa45_50_
     , paymentcla0_.import_session_id as import_46_50_
     , paymentcla0_.last_status_change_date_bank as last_st47_50_
     , paymentcla0_.last_status_change_date_client as last_st48_50_
     , paymentcla0_.migration_created as migrati49_50_
     , paymentcla0_.migration_deleted as migrati50_50_
     , paymentcla0_.migration_updated as migrati51_50_
     , paymentcla0_.collection_outgoing_payment_claim_number as collect52_50_
     , paymentcla0_.operation_type as operati53_50_
     , paymentcla0_.payer_account_number as payer_a54_50_
     , paymentcla0_.payer_account_id as payer_a55_50_
     , paymentcla0_.payer_additional_information as payer_a56_50_
     , paymentcla0_.payer_address as payer_a57_50_
     , paymentcla0_.payer_bank_bic as payer_b58_50_
     , paymentcla0_.payer_bank_corr_account as payer_b59_50_
     , paymentcla0_.payer_bank_name as payer_b60_50_
     , paymentcla0_.payer_bank_place as payer_b61_50_
     , paymentcla0_.payer_bank_id as payer_b62_50_
     , paymentcla0_.payer_client_id as payer_c63_50_
     , paymentcla0_.payer_contractor_inn_kio as payer_c64_50_
     , paymentcla0_.payer_contractor_kpp as payer_c65_50_
     , paymentcla0_.payer_contractor_name as payer_c66_50_
     , paymentcla0_.payer_contractor_id as payer_c67_50_
     , paymentcla0_.payment_code as payment68_50_
     , paymentcla0_.payment_critery_title as payment69_50_
     , paymentcla0_.payment_critery_value as payment70_50_
     , paymentcla0_.payment_critery_id as payment71_50_
     , paymentcla0_.payment_ground_description_description as payment72_50_
     , paymentcla0_.payment_ground_description_id as payment73_50_
     , paymentcla0_.payment_ground_nds as payment74_50_
     , paymentcla0_.payment_ground_nds_calculation_code as payment75_50_
     , paymentcla0_.payment_ground_nds_calculation_description as payment76_50_
     , paymentcla0_.payment_ground_nds_calculation_id as payment77_50_
     , paymentcla0_.payment_ground_nds_percent_percent as payment78_50_
     , paymentcla0_.payment_ground_nds_percent_id as payment79_50_
     , paymentcla0_.payment_ground_operation_code as payment80_50_
     , paymentcla0_.payment_ground_operation_id as payment81_50_
     , paymentcla0_.payment_priority_code as payment82_50_
     , paymentcla0_.payment_priority_id as payment83_50_
     , paymentcla0_.payment_type_code as payment84_50_
     , paymentcla0_.payment_type_description as payment85_50_
     , paymentcla0_.payment_type_id as payment86_50_
     , paymentcla0_.uip_code as uip_cod87_50_
     , paymentcla0_.receipt_date as receipt88_50_
     , paymentcla0_.receiver_account_number as receive89_50_
     , paymentcla0_.receiver_account_id as receive90_50_
     , paymentcla0_.receiver_branch_bic as receive91_50_
     , paymentcla0_.receiver_branch_corr_account as receive92_50_
     , paymentcla0_.receiver_branch_name as receive93_50_
     , paymentcla0_.receiver_branch_place as receive94_50_
     , paymentcla0_.receiver_branch_short_name as receive95_50_
     , paymentcla0_.receiver_branch_id as receive96_50_
     , paymentcla0_.receiver_client_inn as receive97_50_
     , paymentcla0_.receiver_client_short_name as receive98_50_
     , paymentcla0_.receiver_client_id as receive99_50_
     , paymentcla0_.receiver_kpp_kpp as receiv100_50_
     , paymentcla0_.receiver_kpp_id as receiv101_50_
     , paymentcla0_.receiver_message as receiv102_50_
     , paymentcla0_.recipient_official as recipi103_50_
     , paymentcla0_.rejection_viewed as reject104_50_
     , paymentcla0_.reserve as reserv105_50_
     , paymentcla0_.sender_official as sender106_50_
     , paymentcla0_.uuid_edk_command as uuid_e107_50_
     , paymentcla0_.optlock as optloc108_50_
     , paymentcla0_.write_off_date as write_109_50_
  from pc.pc_collection_outgoing_payment_claim paymentcla0_
 where ( paymentcla0_.delete_date is NULL)
   and ($3=$4 or $5=$6 and $7=$8)
   and (paymentcla0_.cabs_doc_ref_ext=$1 or paymentcla0_.cabs_doc_ref=$2);